### ISSUE TITLE
TODO nuspec

### ISSUE THREAD

**Issue by MarcBruins** [MarcBruins/FSCalendar-Xamarin-iOS#1]
Add package to nuget

**Comment by MarcBruins** [comment]
Fixed https://github.com/MarcBruins/FSCalendar-Xamarin-iOS/commit/dfbba365bcaef9f90436893202eb0271b47bff56

**Comment by nileshpatelagile** [comment]
How to use FSCalendar with RTL Support and Hijri calendar for islamic
